version: '3.9'

services:
  web:
    build: ./app
    command: gunicorn django_todo.asgi:application -k uvicorn.workers.UvicornWorker
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
      # - SECRET_KEY: ''
      # - DEBUG: 1
      # - ENVIRONMENT: 'development'