version: '3.9'

services:
  web:
    build: .
    volumes:
    - static_volume:/app/staticfiles
    command: gunicorn django_todo.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
      # - SECRET_KEY: ''
      # - DEBUG: 1
      # - ENVIRONMENT: 'development'
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
    - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume: